const ActionsTypes = {
  DECREASE_APPLE: "DECREASE_APPLE",
  SHAKE_THE_TREE: "SHAKE_THE_TREE",
  STOP_SHAKING: "STOP_SHAKING",
  SHAKING_STATUS: "SHAKING_STATUS",
  NUMBER_OF_APPLES: "NUMBER_OF_APPLES",
  FALLING_APPLE: "FALLING_APPLE",
  DISAPPEAR_APPLE: "DISAPPEAR_APPLE",
  APPLE_ON_BASKET: "APPLE_ON_BASKET",
};
export default {
  ...ActionsTypes,
};
